use_frameworks!

platform :ios, '9.0'

target 'MCSCategory_Example' do
  pod 'MCSCategory', :path => '../'

  target 'MCSCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
